### ISSUE TITLE
[ISSUE] Premake error generating VS 2022 files

### ISSUE THREAD

**Issue by RafaAlkhamry2020** [oxi-dev0/NeuralSim#1]
`C:\Users\hp\Desktop\NeuralSim-main>call vendor\bin\premake\premake5.exe vs2022
Building configurations...
Running action 'vs2022'...
Error: ...lSim-main/vendor/bin/premake/modules/vstudio/vstudio.lua:393: bad argument #2 to 'translate' (string expected, got no value)`

**Comment by oxi-dev0** [comment]
Hiya, this seems to be a premake issue with generating the .vs files. Could you check that you have Visual Studio 2022 installed, and I have uploaded a change to the premake file that may fix the issue... Also, I have only tested it on windows, so it may be an issue with a different os

**Comment by oxi-dev0** [comment]
Also, please could you leave more info, such as your OS and Architecture so I can help you with the issue further :)
