### ISSUE TITLE
Could not open the neural map file

### ISSUE THREAD

**Issue by Lizzit** [oxi-dev0/NeuralSim#5]
I've tried to run the file in various ways as follow:
- C:\NeuralSim-main\bin\Debug>NeuralSim.exe -v [*.NM FILE]
- C:\NeuralSim-main\bin\Debug>NeuralSim.exe -v [0-79-NeuralMap.nm]
- C:\NeuralSim-main\bin\Debug>NeuralSim.exe -v [*.nm]

 But it always throw me the following output:
[11:48:19]: Started Engine
[11:48:19]: Initialised Arguments, Utils and Globals in 0.0002061s
[11:48:19]: Parsed survival shape file in 0.0004231s
[11:48:19]: Could not open the neural map file

What should i do? Can't really figure out....

![Immagine 2022-12-19 115843](https://user-images.githubusercontent.com/45573181/208411103-d1a6a4fe-ee4b-4663-a173-2d3bc4442ae1.png)

**Comment by oxi-dev0** [comment]
hi, sorry, i might have made the documentation unclear for command line arguments, but the square brackets are only in the documentation to show there is a token. In your case, you want to run `NeuralSim.exe -v out/0-79-NeuralMap.nm`. Also, the visualise functionality doesnt support wildcards (*), it needs a specific file.

**Comment by Lizzit** [comment]
I'd tried to do that too but it wasn't working. Right now i tried again and it worked! Thank you!

**Comment by oxi-dev0** [comment]
Glad i could help!
